### ISSUE TITLE
converturls does not deal well with non-http urls

### ISSUE THREAD

**Issue by meinharrd** [liip/LiipUrlAutoConverterBundle#10]
hello there,

current behaviour:
- urls like `ftp://example.org` or `something://example.org` will be converted to `<a href="http://ftp://example.org" class="" target="_blank">ftp://example.org</a>` and `<a href="http://something://example.org" class="" target="_blank">something://example.org</a>`

expected behaviour:
- `something://example.org` -> `<a href="something://example.org" class="" target="_blank">something://example.org</a>`

**Comment by dbu** [comment]
we are not really maintaining this library anymore because nobody at liip is currently using it. it is not up to date with recent symfony versions, not tested on php 7.1 or newer and so on. the travis-ci build fails for the antique php versions and obsolete symfony versions.

in our opinion, the evolution should be to use an existing library for finding urls in text, or splitting out the logic implemented here into a library and have the bundle only integrate the library into symfony.

we archive this bundle now.
