### ISSUE TITLE
rel="nofollow"

### ISSUE THREAD

**Issue by jakenoble** [liip/LiipUrlAutoConverterBundle#23]
Is there any support for rel="nofollow" or can you advise how I can add this without overwriting the Liip core files?

**Comment by lsmith77** [comment]
you want to add ``rel="nofollow"`` to links automatically? I don't think we currently have a solution for this .. maybe using a custom class and some javascript it can work, but I assume you are more interested in stopping search engines? at any rate, this Bundle is currently stuck a bit in limbo as we are not getting done with https://github.com/liip/LiipUrlAutoConverterBundle/pull/14

**Comment by jakenoble** [comment]
It seems to OK fine apart from the rel issue. Which I created by making my own Extension

**Comment by dbu** [comment]
we are not really maintaining this library anymore because nobody at liip is currently using it. it is not up to date with recent symfony versions, not tested on php 7.1 or newer and so on. the travis-ci build fails for the antique php versions and obsolete symfony versions.

in our opinion, the evolution should be to use an existing library for finding urls in text, or splitting out the logic implemented here into a library and have the bundle only integrate the library into symfony.

we archive this bundle now.
