### ISSUE TITLE
Does not match new TLDs

### ISSUE THREAD

**Issue by jakenoble** [liip/LiipUrlAutoConverterBundle#24]
The .directory TLD is not matched. Because of this regex

`[a-z]{2,4}`

**Comment by lsmith77** [comment]
yeah .. this is a super nightmare for this kind of case. i guess its necessary to work with an explicit list of TLDs because just allowing more characters after a dot is going to lead to a lot more false positives.

that being said, this Bundle should adopt a general purpose library (see the open PRs) rather than trying to invent one on its own.

**Comment by jakenoble** [comment]
Will #14 be fixed/merged?

**Comment by paolotremadio** [comment]
+1, all the new TLDs are not matched. Creating a list is almost impossible, there're new TLDs added every months and there's support for non-ascii characters (e.g. https://www.eurodns.com/international-domain-names/xn--3ds443g-domain-registration/, https://www.eurodns.com/international-domain-names/xn--ngbc5azd-domain-registration/ and https://www.eurodns.com/international-domain-names/xn--i1b6b1a6a2e-domain-registration/)

**Comment by dbu** [comment]
we are not really maintaining this library anymore because nobody at liip is currently using it. it is not up to date with recent symfony versions, not tested on php 7.1 or newer and so on. the travis-ci build fails for the antique php versions and obsolete symfony versions.

in our opinion, the evolution should be to use an existing library for finding urls in text, or splitting out the logic implemented here into a library and have the bundle only integrate the library into symfony.

we archive this bundle now.
