### ISSUE TITLE
Remove support for domains without scheme

### ISSUE THREAD

**Issue by sagikazarmark** [liip/LiipUrlAutoConverterBundle#31]
You cannot safely decide whether it is a URL or just a dot in the middle of something.

**Comment by lsmith77** [comment]
yeah .. but its still something that most people expect .. that ``foo.com`` would be linked.
overall however I think this Bundle needs to be reworked to be more flexible and likely based on a solid library.

**Comment by sagikazarmark** [comment]
Well, I've done some research, and most libraries I found don't support links without a protocol. It is certainly possible (for example Slack does it quite well).

Libraries I treat as usable ones:
https://github.com/asika32764/php-autolink
https://github.com/nojimage/twitter-text-php
https://github.com/Madlines/Common-AutoLink

Although I can't say they are solid.

The author of lib_autolink asked a valid question: what about supported TLDs, do they need a path or something?

Possible answer: https://github.com/umpirsky/tld-list

Not sure if I will have the time, but if I have, do you accept a complete rework PR?

**Comment by lsmith77** [comment]
yes I am open to a complete rework

**Comment by sagikazarmark** [comment]
Okay, I will see what I can do.

**Comment by dbu** [comment]
we are not really maintaining this library anymore because nobody at liip is currently using it. it is not up to date with recent symfony versions, not tested on php 7.1 or newer and so on. the travis-ci build fails for the antique php versions and obsolete symfony versions.

in our opinion, the evolution should be to use an existing library for finding urls in text, or splitting out the logic implemented here into a library and have the bundle only integrate the library into symfony.

we archive this bundle now.
